
INSERT INTO PRODUCT(PRODUCT_ID, BRAND, PRODUCTNAME, CATEGORY, COLOR, PRICE, PURCHASEDATE, EXPIRATIONDATE, USEDUP, REPURCHASE, REVIEW) VALUES(1, 'Nars', 'Sheer Glow Foundation', 'Face', 'Bisque', 40.00, '2016-02-10', '2018-02-10', false, false, 'OK');
INSERT INTO PRODUCT(PRODUCT_ID, BRAND, PRODUCTNAME, CATEGORY, COLOR, PRICE, PURCHASEDATE, EXPIRATIONDATE, USEDUP, REPURCHASE, REVIEW) VALUES(2, 'Urban Decay', 'Revolution Lipstick', 'Lips', 'Ruby Red', 18.00, '2016-02-10', '2018-02-10', false, false, 'OK');
INSERT INTO PRODUCT(PRODUCT_ID, BRAND, PRODUCTNAME, CATEGORY, COLOR, PRICE, PURCHASEDATE, EXPIRATIONDATE, USEDUP, REPURCHASE, REVIEW) VALUES(3, 'Stila', 'Liquid Eyeliner', 'Eyes', 'Black', 18.00, '2016-02-10', '2018-02-10', false, false, 'OK');
INSERT INTO PRODUCT(PRODUCT_ID, BRAND, PRODUCTNAME, CATEGORY, COLOR, PRICE, PURCHASEDATE, EXPIRATIONDATE, USEDUP, REPURCHASE, REVIEW) VALUES(4, 'Becca', 'EverMatte Primer', 'Face', 'Clear', 42.00, '2016-02-10', '2018-02-10', false, false, 'OK');


















